### ISSUE TITLE
I wrote a Python SDK for Gospeed API.

### ISSUE THREAD

**Issue by tick97115115** [GopeedLab/docs#7]
Would you like to add that project link to Gospeed document?

**Comment by tick97115115** [comment]
https://github.com/tick97115115/gospeed_api

**Comment by monkeyWie** [comment]
Certainly, this is very useful, thanks~

**Comment by monkeyWie** [comment]
Updated in https://github.com/GopeedLab/docs/commit/583deba29c51fe0737e5058a947e091d92a0b643

**Comment by tick97115115** [comment]
Glad to help❤️
