### ISSUE TITLE
gospeed dev 对单个小文件不停下载的问题

### ISSUE THREAD

**Issue by hhy06** [GopeedLab/docs#9]
最近常有gospeed 客户端连接到utorrent并不断下载，产生大量流浪，哪怕这个文件其实挺小。
![image](https://github.com/user-attachments/assets/624971de-0c04-4b0c-91e2-2eada6dda360)
如图，上面其实是一个几mb的小文件，但gospeed可以反复下载出几gb。不得不对其限速。

**Comment by monkeyWie** [comment]
参考：https://github.com/GopeedLab/gopeed/discussions/650
